# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-09 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users_who_like',
        ),
    ]
